### Get semua user
GET http://localhost:8080/users
Host: 8080

### Get user ID tertentu
GET http://localhost:8080/users/1
Host: 8080

### Tambah user baru
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Jawir"
}

### Perbarui nama user
PATCH http://localhost:8080/users/3
Content-Type: application/json

{
  "name": "Yoga Dev",
  "email": "yoga@gmail.com",
  "password": "rahasiaBaru"
}


### Delete User
DELETE http://localhost:8080/users/3
Host: 8080

### Register user
POST http://localhost:8080/auth/register
Content-Type: application/x-www-form-urlencoded

name=Yoga&email=yoga@gmail.com&password=12345

### Login user
POST  http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

email=yoga@gmail.com&password=12345

